plugins {
    id 'java'
}

group = 'com.mineplus'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT"
    implementation "org.joml:joml:1.10.8"
    implementation "com.google.code.gson:gson:2.11.0"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(21)
}

processResources {
    inputs.property("version", project.version)
    filteringCharset = 'UTF-8'

    filesMatching("plugin.yml") {
        expand(version: project.version)
    }
}
