package com.mineplus.pack.compile;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.mineplus.infrastructure.virtual.BakedCube;
import com.mineplus.infrastructure.virtual.BakedFace;
import com.mineplus.infrastructure.virtual.CubeFace;
import com.mineplus.infrastructure.virtual.ModelMeta;
import com.mineplus.infrastructure.virtual.VirtualModel;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Serializes a Mineplus {@link VirtualModel} — the runtime asset graph the
 * importer already produced — into a vanilla client element-model JSON file.
 * The bbmodel stays the authoring input; this writer never re-parses it.
 *
 * <p>Space mapping: a cube's {@code translation} is its model-space offset in
 * blocks and {@code scale} its extents, relative to the anchor convention.
 * CENTER models anchor px (0,0,0) at the block center base (vanilla element
 * space shift {@code (-8, 0, -8)}), GRID models at the block corner (no
 * shift). UVs are texture pixels at the model's resolution, converted to the
 * vanilla 0..16 UV window via {@code 16 / resolution}.</p>
 *
 * <p>Honest degradation: vanilla elements are axis-aligned boxes with at most
 * one ±45° rotation, so cubes carrying a non-trivial rotation are emitted as
 * their axis-aligned bounding boxes and reported once per model — never as a
 * crash, never silently. Wrapping UV windows (span &gt; texture) are clamped
 * the same way.</p>
 */
public final class ModelJsonWriter {

    private static final Gson GSON = new GsonBuilder().disableHtmlEscaping().create();

    private ModelJsonWriter() {
    }

    /**
     * @param model       the imported model
     * @param originMode  resolved anchor convention for {@code model}
     * @param outNamespace namespace the texture references point into
     */
    public static String write(VirtualModel model, ModelMeta.OriginMode originMode, String outNamespace) {
        List<String> warnings = new ArrayList<>();
        String json = write(model, originMode, outNamespace, warnings);
        for (String warning : warnings) {
            com.mineplus.util.DebugLogger.warning("[PackCompiler] Model '" + model.name() + "': " + warning);
        }
        return json;
    }

    /** Same as {@link #write(VirtualModel, ModelMeta.OriginMode, String)} with a warning sink (for tests/tooling). */
    public static String write(
            VirtualModel model,
            ModelMeta.OriginMode originMode,
            String outNamespace,
            List<String> warnings
    ) {
        Map<String, String> textureIndex = new LinkedHashMap<>();
        JsonArray elements = new JsonArray();
        for (BakedCube cube : model.cubes()) {
            JsonObject element = element(cube, model, originMode, textureIndex, warnings);
            if (element != null) {
                elements.add(element);
            }
        }

        JsonObject textures = new JsonObject();
        for (Map.Entry<String, String> entry : textureIndex.entrySet()) {
            textures.addProperty(entry.getValue(), outNamespace + ":" + entry.getKey());
        }
        if (!textureIndex.isEmpty()) {
            textures.addProperty("particle", outNamespace + ":" + textureIndex.keySet().iterator().next());
        }

        JsonObject root = new JsonObject();
        root.addProperty("credit", "Generated by Mineplus");
        root.addProperty("ambientocclusion", false);
        root.add("textures", textures);
        root.add("elements", elements);
        root.add("display", vanillaDisplayTransforms());
        return GSON.toJson(root);
    }

    private static JsonObject element(
            BakedCube cube,
            VirtualModel model,
            ModelMeta.OriginMode originMode,
            Map<String, String> textureIndex,
            List<String> warnings
    ) {
        if (!cube.isAxisAligned()) {
            warnings.add("cube '" + cube.name() + "' carries a rotation; emitted as its axis-aligned "
                    + "bounding box (vanilla elements support at most one ±45° axis rotation).");
        }

        float originShiftX = originMode == ModelMeta.OriginMode.CENTER ? -8.0f : 0.0f;
        float originShiftY = 0.0f;
        float originShiftZ = originMode == ModelMeta.OriginMode.CENTER ? -8.0f : 0.0f;

        float fromX = cube.translation().x * 16.0f + originShiftX;
        float fromY = cube.translation().y * 16.0f + originShiftY;
        float fromZ = cube.translation().z * 16.0f + originShiftZ;
        float toX = fromX + cube.scale().x * 16.0f;
        float toY = fromY + cube.scale().y * 16.0f;
        float toZ = fromZ + cube.scale().z * 16.0f;

        JsonObject element = new JsonObject();
        element.addProperty("name", cube.name());
        element.add("from", vec3(round(fromX), round(fromY), round(fromZ)));
        element.add("to", vec3(round(toX), round(toY), round(toZ)));
        element.addProperty("shade", false);

        JsonObject faces = new JsonObject();
        for (CubeFace faceKey : CubeFace.values()) {
            BakedFace face = cube.faces().get(faceKey);
            if (face == null || face.textureName() == null || face.textureName().isBlank()) {
                continue;
            }
            faces.add(faceKey.name().toLowerCase(java.util.Locale.ROOT), face(face, model, textureIndex, warnings));
        }
        element.add("faces", faces);
        return element;
    }

    private static JsonObject face(
            BakedFace face,
            VirtualModel model,
            Map<String, String> textureIndex,
            List<String> warnings
    ) {
        float uScale = 16.0f / model.resolution().width();
        float vScale = 16.0f / model.resolution().height();

        float u1 = clampUv(face.u1() * uScale, warnings, face);
        float v1 = clampUv(face.v1() * vScale, warnings, face);
        float u2 = clampUv(face.u2() * uScale, warnings, face);
        float v2 = clampUv(face.v2() * vScale, warnings, face);
        if (u2 < u1) {
            float swap = u1;
            u1 = u2;
            u2 = swap;
        }
        if (v2 < v1) {
            float swap = v1;
            v1 = v2;
            v2 = swap;
        }

        String index = textureIndex.computeIfAbsent(face.textureName(),
                name -> "#" + textureIndex.size());

        JsonObject json = new JsonObject();
        JsonArray uv = new JsonArray();
        uv.add(round(u1));
        uv.add(round(v1));
        uv.add(round(u2));
        uv.add(round(v2));
        json.add("uv", uv);
        json.addProperty("texture", index);
        int rotation = ((face.rotation() % 360) + 360) % 360;
        if (rotation != 0) {
            json.addProperty("rotation", rotation);
        }
        return json;
    }

    private static float clampUv(float value, List<String> warnings, BakedFace face) {
        if (value < -1.0e-3f || value > 16.0f + 1.0e-3f) {
            warnings.add("face texture '" + face.textureName() + "' has a wrapping UV window; clamped to 0..16.");
        }
        return Math.max(0.0f, Math.min(16.0f, value));
    }

    private static JsonObject vanillaDisplayTransforms() {
        JsonObject display = new JsonObject();
        display.add("gui", displayEntry(new float[]{30, 225, 0}, new float[]{0, 0, 0}, new float[]{0.625f, 0.625f, 0.625f}));
        display.add("ground", displayEntry(new float[]{0, 0, 0}, new float[]{0, 3, 0}, new float[]{0.25f, 0.25f, 0.25f}));
        display.add("head", displayEntry(new float[]{0, 180, 0}, new float[3], new float[]{1, 1, 1}));
        display.add("fixed", displayEntry(new float[3], new float[3], new float[]{1, 1, 1}));
        display.add("thirdperson_righthand", displayEntry(new float[]{75, 45, 0}, new float[]{0, 2.5f, 0}, new float[]{0.375f, 0.375f, 0.375f}));
        display.add("thirdperson_lefthand", displayEntry(new float[]{75, 225, 0}, new float[]{0, 2.5f, 0}, new float[]{0.375f, 0.375f, 0.375f}));
        display.add("firstperson_righthand", displayEntry(new float[]{0, 45, 0}, new float[3], new float[]{0.40f, 0.40f, 0.40f}));
        display.add("firstperson_lefthand", displayEntry(new float[]{0, 225, 0}, new float[3], new float[]{0.40f, 0.40f, 0.40f}));
        return display;
    }

    private static JsonObject displayEntry(float[] rotation, float[] translation, float[] scale) {
        JsonObject entry = new JsonObject();
        entry.add("rotation", vec3(rotation));
        entry.add("translation", vec3(translation));
        entry.add("scale", vec3(scale));
        return entry;
    }

    private static JsonArray vec3(float... values) {
        JsonArray array = new JsonArray();
        for (float value : values) {
            array.add(round(value));
        }
        return array;
    }

    private static float round(float value) {
        return Math.round(value * 1000.0f) / 1000.0f;
    }
}
